-- migrations/2026_07_multimarcas_historico.sql
CREATE TABLE IF NOT EXISTS multimarcas_historico (
    id INT NOT NULL AUTO_INCREMENT,
    temporada VARCHAR(20) NOT NULL,
    fecha_snapshot DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_multimarca INT NOT NULL,
    clave VARCHAR(20) NOT NULL,
    evac VARCHAR(20),
    cliente_razon_social VARCHAR(255),
    avance_global DECIMAL(15,2) DEFAULT 0.00,
    avance_global_scott DECIMAL(15,2) DEFAULT 0.00,
    avance_global_syncros DECIMAL(15,2) DEFAULT 0.00,
    avance_global_apparel DECIMAL(15,2) DEFAULT 0.00,
    avance_global_vittoria DECIMAL(15,2) DEFAULT 0.00,
    avance_global_bold DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_julio DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_agosto DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_septiembre DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_octubre DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_noviembre DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_diciembre DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_enero DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_febrero DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_marzo DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_abril DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_mayo DECIMAL(15,2) DEFAULT 0.00,
    total_facturas_junio DECIMAL(15,2) DEFAULT 0.00,
    PRIMARY KEY (id),
    KEY idx_temporada (temporada)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
