-- Archivo histórico de tabla_retroactivos por temporada.
-- tabla_retroactivos nunca se había archivado antes: es una tabla en vivo
-- que se sobreescribe en cada sincronización (ejecutar_sincronizacion_y_calculos),
-- así que MY26 no tiene snapshot -- solo a partir de esta migración las
-- temporadas que se cierren quedarán respaldadas aquí.
CREATE TABLE IF NOT EXISTS tabla_retroactivos_historico (
    id INT AUTO_INCREMENT PRIMARY KEY,
    temporada VARCHAR(20) NOT NULL,
    fecha_snapshot DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_original INT,
    id_previo INT,
    CLAVE VARCHAR(20),
    ZONA VARCHAR(20),
    CLIENTE VARCHAR(255),
    CATEGORIA VARCHAR(50),
    COMPRA_MINIMA_ANUAL DECIMAL(15,2),
    COMPRA_MINIMA_APPAREL DECIMAL(15,2),
    COMPRAS_TOTALES_CRUDO DECIMAL(15,2),
    META_MY26_CUMPLIDA INT,
    COMPRA_GLOBAL_SCOTT DECIMAL(15,2),
    COMPRA_GLOBAL_APPAREL DECIMAL(15,2),
    COMPRA_GLOBAL_BOLD DECIMAL(15,2),
    TOTAL_ACUMULADO DECIMAL(17,2),
    notas_credito DECIMAL(15,2),
    garantias DECIMAL(15,2),
    productos_ofertados DECIMAL(15,2),
    bicicleta_demo DECIMAL(15,2),
    bicicletas_bold DECIMAL(15,2),
    importe_final DECIMAL(15,2),
    compra_anual_crudo DECIMAL(15,2),
    compra_adicional DECIMAL(15,2),
    porcentaje_retroactivo DECIMAL(6,4),
    porcentaje_retroactivo_apparel DECIMAL(6,4),
    retroactivo_total DECIMAL(15,4),
    importe DECIMAL(15,2),
    estatus VARCHAR(20),
    fecha_aplicacion DATE,
    NC VARCHAR(50),
    FACT VARCHAR(50),
    temporada_cerrada TINYINT(1) DEFAULT 0,
    fecha_cierre_temporada DATETIME NULL,
    fecha_cierre_apparel DATE NULL,
    INDEX idx_temporada (temporada)
);
